[preface]
== Preface

This book is an addendum to the __Mastering Automation in CloudForms 4.2 and ManageIQ Euwe__ book, covering the new automate features and functionality available with CloudForms 4.5 & 4.6 (ManageIQ _Fine_ & _Gaprindashvili_)




==== Acknowledgements

Several people have contributed code samples and ideas to this addendum, including Christian Jung, Jeff Warnica, Ian Tewksbury, Brant Evans and Jason Ritenour from Red Hat.



=== Conventions Used in This Addendum
////
Let me know if you need to edit this section.
////
The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions, path and object names within the Automate Datastore, Schema field values

*Bold*:: Indicates WebUI components, event names, Schema field names

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.

[NOTE]
====
This icon signifies a general note.
====

[TIP]
====
This icon signifies a tip or suggestion
====

[WARNING]
====
This icon indicates a warning or caution.
====







